-- Esquema inicial de BeanFlow (cafetería). Sintaxis portable PostgreSQL/H2 —
-- cada cambio futuro del modelo va en una migración nueva (V2__*.sql),
-- nunca editando esta.

-- Roles del negocio (heredados del diseño original de BeanFlow):
-- admin (todo) · garzon (mesas y comandas) · cocina (preparación) · caja (cobro).
CREATE TABLE usuarios (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo      VARCHAR(255) NOT NULL,
    nombre      VARCHAR(255) NOT NULL,
    clave_hash  VARCHAR(255) NOT NULL,
    rol         VARCHAR(255) NOT NULL DEFAULT 'garzon',
    activo      BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_usuarios_correo UNIQUE (correo)
);

CREATE TABLE categorias (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_categorias_nombre UNIQUE (nombre)
);

-- Materia prima: lo que se descuenta al preparar (café en grano, leche, vasos).
-- No se vende directamente; su stock vive aquí y solo se mueve por el libro.
CREATE TABLE insumos (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre         VARCHAR(255) NOT NULL,
    unidad         VARCHAR(16) NOT NULL,
    stock          NUMERIC(12, 3) NOT NULL DEFAULT 0,
    stock_minimo   NUMERIC(12, 3) NOT NULL DEFAULT 0,
    costo_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    activo         BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_insumos_nombre UNIQUE (nombre),
    CONSTRAINT ck_insumos_unidad CHECK (unidad IN ('g', 'ml', 'unidad')),
    CONSTRAINT ck_insumos_stock CHECK (stock >= 0)
);

-- Lo que el cliente pide de la carta. El stock NO vive aquí: se deriva de los
-- insumos de su receta (un capuchino "hay" mientras alcancen café y leche).
CREATE TABLE productos (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_id         BIGINT NOT NULL,
    nombre               VARCHAR(255) NOT NULL,
    descripcion          TEXT,
    precio               NUMERIC(12, 2) NOT NULL,
    requiere_preparacion BOOLEAN NOT NULL DEFAULT TRUE,
    activo               BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_productos_nombre UNIQUE (nombre),
    CONSTRAINT fk_productos_categoria FOREIGN KEY (categoria_id) REFERENCES categorias (id),
    CONSTRAINT ck_productos_precio CHECK (precio >= 0)
);

-- Receta: cuánto insumo consume una unidad del producto.
CREATE TABLE receta_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_id BIGINT NOT NULL,
    insumo_id   BIGINT NOT NULL,
    cantidad    NUMERIC(12, 3) NOT NULL,
    CONSTRAINT uq_receta_producto_insumo UNIQUE (producto_id, insumo_id),
    CONSTRAINT fk_receta_producto FOREIGN KEY (producto_id) REFERENCES productos (id) ON DELETE CASCADE,
    CONSTRAINT fk_receta_insumo FOREIGN KEY (insumo_id) REFERENCES insumos (id),
    CONSTRAINT ck_receta_cantidad CHECK (cantidad > 0)
);

CREATE TABLE mesas (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero INTEGER NOT NULL,
    nombre VARCHAR(255),
    activa BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_mesas_numero UNIQUE (numero)
);

-- Cuenta abierta de una mesa. mesa_id nulo = venta de mostrador (para llevar).
CREATE TABLE comandas (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mesa_id          BIGINT,
    estado           VARCHAR(16) NOT NULL DEFAULT 'abierta',
    total            NUMERIC(12, 2) NOT NULL DEFAULT 0,
    metodo_pago      VARCHAR(16),
    nota             TEXT,
    abierta_por_id   BIGINT NOT NULL,
    cobrada_por_id   BIGINT,
    abierta_en       TIMESTAMP WITH TIME ZONE NOT NULL,
    cerrada_en       TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_comandas_mesa FOREIGN KEY (mesa_id) REFERENCES mesas (id),
    CONSTRAINT fk_comandas_abierta_por FOREIGN KEY (abierta_por_id) REFERENCES usuarios (id),
    CONSTRAINT fk_comandas_cobrada_por FOREIGN KEY (cobrada_por_id) REFERENCES usuarios (id),
    CONSTRAINT ck_comandas_estado CHECK (estado IN ('abierta', 'cobrada', 'anulada'))
);


CREATE INDEX ix_comandas_estado ON comandas (estado);

-- Línea de la comanda. Congela nombre y precio: cambiar la carta mañana no
-- debe reescribir lo que el cliente pidió hoy.
CREATE TABLE comanda_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comanda_id      BIGINT NOT NULL,
    producto_id     BIGINT NOT NULL,
    nombre_producto VARCHAR(255) NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL,
    cantidad        INTEGER NOT NULL,
    estado          VARCHAR(16) NOT NULL DEFAULT 'pendiente',
    nota            TEXT,
    creado_en       TIMESTAMP WITH TIME ZONE NOT NULL,
    listo_en        TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_comanda_items_comanda FOREIGN KEY (comanda_id) REFERENCES comandas (id) ON DELETE CASCADE,
    CONSTRAINT fk_comanda_items_producto FOREIGN KEY (producto_id) REFERENCES productos (id),
    CONSTRAINT ck_comanda_items_cantidad CHECK (cantidad > 0),
    CONSTRAINT ck_comanda_items_estado
        CHECK (estado IN ('pendiente', 'preparando', 'listo', 'entregado', 'anulado'))
);

CREATE INDEX ix_comanda_items_comanda ON comanda_items (comanda_id);
CREATE INDEX ix_comanda_items_estado ON comanda_items (estado);

-- Libro de inventario: toda variación de stock deja firma (quién, por qué).
-- El saldo resultante se graba en la fila para auditar sin recalcular.
CREATE TABLE movimientos_insumo (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insumo_id         BIGINT NOT NULL,
    tipo              VARCHAR(16) NOT NULL,
    cantidad          NUMERIC(12, 3) NOT NULL,
    stock_resultante  NUMERIC(12, 3) NOT NULL,
    motivo            VARCHAR(255),
    usuario_id        BIGINT,
    comanda_item_id   BIGINT,
    creado_en         TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_movimientos_insumo FOREIGN KEY (insumo_id) REFERENCES insumos (id),
    CONSTRAINT fk_movimientos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT ck_movimientos_tipo CHECK (tipo IN ('entrada', 'salida', 'ajuste', 'merma'))
);

CREATE INDEX ix_movimientos_insumo ON movimientos_insumo (insumo_id);
CREATE INDEX ix_movimientos_creado ON movimientos_insumo (creado_en);
